# Generated by Django 5.0 on 2023-12-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('deliver', 'Deliver')], default='client', max_length=10),
        ),
    ]
